# -*- coding: utf-8 -*-
"""Untitled42.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nvPZRtLDa6GA7dVljatSb2vFfM5nmNpZ
"""

# 1. Imports
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

# 2. Load data
iris = load_iris()
X = iris.data
y = iris.target
feature_names = iris.feature_names
target_names = iris.target_names

# 3. EDA (optional, can be skipped in production)
df = pd.DataFrame(X, columns=feature_names)
df['species'] = pd.Categorical.from_codes(y, target_names)
print(df.head())
print(df.info())

# 4. Split and scale
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

# 5. Model evaluation function
def evaluate_model(model, X_train, X_test, y_train, y_test, name):
    model.fit(X_train, y_train)
    y_pred = model.predict(X_test)
    acc = accuracy_score(y_test, y_pred)
    print(f"\n{name} Accuracy: {acc:.4f}")
    print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred))
    print("Classification Report:\n", classification_report(y_test, y_pred, target_names=target_names))
    return acc

# 6. Train and evaluate multiple models
models = [
    (LogisticRegression(max_iter=200), "Logistic Regression", True),
    (KNeighborsClassifier(n_neighbors=5), "KNN (k=5)", True),
    (DecisionTreeClassifier(random_state=42), "Decision Tree", False),
    (RandomForestClassifier(n_estimators=100, random_state=42), "Random Forest", False),
    (SVC(kernel='rbf', random_state=42), "SVM (RBF)", True)
]

results = {}
for model, name, scale in models:
    if scale:
        acc = evaluate_model(model, X_train_scaled, X_test_scaled, y_train, y_test, name)
    else:
        acc = evaluate_model(model, X_train, X_test, y_train, y_test, name)
    results[name] = acc

# 7. Hyperparameter tuning on SVM
print("\n--- Hyperparameter Tuning for SVM ---")
param_grid = {'C': [0.1, 1, 10, 100], 'gamma': [1, 0.1, 0.01, 0.001], 'kernel': ['rbf']}
grid = GridSearchCV(SVC(), param_grid, cv=5, verbose=0)
grid.fit(X_train_scaled, y_train)
print("Best parameters:", grid.best_params_)
print("Tuned SVM test accuracy:", accuracy_score(y_test, grid.predict(X_test_scaled)))

# 8. Feature importance from Random Forest
rf = RandomForestClassifier(n_estimators=100, random_state=42)
rf.fit(X_train, y_train)
importances = rf.feature_importances_
indices = np.argsort(importances)[::-1]
plt.figure(figsize=(8,4))
plt.title("Feature Importances (Random Forest)")
plt.bar(range(X.shape[1]), importances[indices], align="center")
plt.xticks(range(X.shape[1]), np.array(feature_names)[indices], rotation=45)
plt.tight_layout()
plt.show()